Repository octokit/plugin-paginate-rest.js, pull requests merged in 2022-07, with the labels that each got.

#403 ci: stop testing against NodeJS v10, v12
  .github/workflows/test.yml
  package.json
Labels: blocked, maintenance

#407 ci(test): use test_matrix and test jobs
  .github/workflows/test.yml
Labels: maintenance

#409 ci(codeql): remove `git checkout HEAD^2`
  .github/workflows/codeql.yml
Labels: maintenance

#411 [deps] updates pika/pack to a non vulnerable version
  package-lock.json
  package.json
Labels: dependencies, maintenance

#420 fix: revert change to `@octokit/core` peer dependency
  package.json
Labels: bug
